name: get_cli
version: 1.9.1
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  #  archive: ^3.1.2
  ansicolor: 
  collection: 
  dart_style: 
  dcli: 
  http: 
  intl: 
  meta: 
  path: 
  process_run: 
  pubspec_parse: 
  pub_semver: 
  recase:
  version: 
  yaml: 

dev_dependencies:
  lints: 
  test: 

executables:
  get: get
  getx: get
